name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Definir TAG
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build da imagem
        run: |
          docker build \
            -f Dockerfile.lambda \
            -t $ECR_REPOSITORY:$IMAGE_TAG .

      - name: Subir container para teste
        run: |
          docker run -d \
            --name api-consulta-processo \
            -p 3000:3000 \
            -e ASPNETCORE_URLS=http://+:3000 \
            -e ASPNETCORE_ENVIRONMENT=Development \
            $ECR_REPOSITORY:$IMAGE_TAG


      - name: Aguardar API iniciar
        run: |
          for i in {1..30}; do

            if curl -fs http://localhost:3000/health; then
              echo "API funcionando"
              exit 0
            fi

            echo "Aguardando API..."
            sleep 2

          done

          echo "API não iniciou"
          docker logs api-consulta-processo
          exit 1


      - name: Parar container de teste
        if: always()
        run: |
          docker stop api-consulta-processo || true
          docker rm api-consulta-processo || true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Criar tag SHA para o ECR
        run: |
          docker tag \
            $ECR_REPOSITORY:$IMAGE_TAG \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Criar tag latest
        run: |
          docker tag \
            $ECR_REPOSITORY:$IMAGE_TAG \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push da imagem (SHA)
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Push da imagem (latest)
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Atualizar Lambda
        run: |
          aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
          --image-uri \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Esperar atualização
        run: |
          aws lambda wait function-updated \
          --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }}